# Generated by Django 5.0.6 on 2024-09-05 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('stock_branch', models.CharField(choices=[('Matugga', 'Matugga'), ('Mukono', 'Mukono')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('issued_to', models.CharField(max_length=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('recieved_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('method_of_sale', models.CharField(choices=[('cash', 'cash'), ('Credit', 'Credit')], max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.stock')),
            ],
        ),
    ]
