# Generated by Django 5.0.6 on 2024-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('cash', 'cash'), ('Credit', 'Credit')], default='Cash', max_length=50),
        ),
    ]
