# Generated by Django 5.0.6 on 2024-09-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0002_sale_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='method_of_sale',
        ),
    ]
